name: Generate Release APK

on:
  # releaseブランチ更新時に起動する
  push:
    branches: [ release ]
  # 手動実行ボタン
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    # releaseブランチをチェックアウト
    - uses: actions/checkout@v2
      with:
        ref: 'release'

    # JDK導入
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    # 権限を与える
    - name: Grant permission gradlew
      run: chmod +x gradlew
      
    # コマンドラインからAPKの作成。実行前に環境変数をGitHubActionsのSecretから取得
    - name: Building APK
      env:
        ENV_SIGN_KEYSTORE_BASE64: ${{secrets.ENV_SIGN_KEYSTORE_BASE64}}
        ENV_SIGN_KEY_ALIAS: ${{secrets.ENV_SIGN_KEY_ALIAS}}
        ENV_SIGN_KEY_PASSWORD: ${{secrets.ENV_SIGN_KEY_PASSWORD}}
        ENV_SIGN_STORE_PASSWORD: ${{secrets.ENV_SIGN_STORE_PASSWORD}}
      run: ./gradlew assembleRelease

    # アーティファクトとして保存
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
